---
title: '932'
author: "Juan Jimenez"
date: '2022-03-03'
output: html_document
---

```{r}
#3. Calculate the Fst value for each site and visualize the results
geno <- read.table("largedata/geno.txt", header=FALSE)
names(geno) <- c("chr", "pos", "ref", "alt", "l1", "l2", "l3", "l4", "l5")
for(i in 5:9){
  # replace slash and everything after it as nothing
  geno$newcol <- gsub("/.*", "", geno[,i] )
  # extract the line name
  nm <- names(geno)[i]
  # assign name for this allele
  names(geno)[ncol(geno)] <- paste0(nm, sep="_a1")
  geno$newcol <- gsub(".*/", "", geno[,i] )
  names(geno)[ncol(geno)] <- paste0(nm, sep="_a2")
}

geno$p <- apply(geno[, 10:19], 1, function(x) {sum(as.numeric(as.character(x)))})
geno$p <- geno$p/10
geno$p1 <- apply(geno[, 10:15], 1, function(x) {sum(as.numeric(as.character(x)))})
geno$p1 <- geno$p1/6
geno$p2 <- apply(geno[, 16:19], 1, function(x) {sum(as.numeric(as.character(x)))})
geno$p2 <- geno$p2/4

geno$fst <- with(geno, ((p1-p)^2 + (p2-p)^2)/(2*p*(1-p)) )

write.table(geno, "cache/fst.csv", sep=",", row.names = FALSE, quote=FALSE)

fst <- read.csv("cache/fst.csv")
plot(fst$pos, fst$fst, xlab="Physical position", ylab="Fst value", main="")



```

#from here

```{r}
#setup working directory
setwd("D:/Documents/GitHub/Assignment_1_AGRO932/")
#reading the sequence data
geno <- read.table("geno.txt", header=FALSE)

```

```{r}
#Calculate the Fst value for each site and visualize the results
#to check the dimension of the matrix
dim(geno)
names(geno) <- c("chr", "pos", "ref", "alt", "l1", "l2", "l3", "l4", "l5", "l6", "l7", "l8", "l9", "l10", "l11", "l12", "l13", "l14", "l15", "l16", "l17", "l18", "l19", "l20")
#again to check the dimension of the matrix
dim(geno)
#to start reading from column#5 because here is where the sequence data of the population start
for(i in 5:24){
  # replace slash and everything after it as nothing
  geno$newcol <- gsub("/.*", "", geno[,i] )
  # extract the line name
  nm <- names(geno)[i]
  # assign name for this allele
  names(geno)[ncol(geno)] <- paste0(nm, sep="_a1")
  geno$newcol <- gsub(".*/", "", geno[,i] )
  names(geno)[ncol(geno)] <- paste0(nm, sep="_a2")
}

```



```{r}
#to compute p and do populations p1 and p2
geno$p <- apply(geno[, 25:64], 1, function(x) {sum(as.numeric(as.character(x)))})
geno$p <- geno$p/40
geno$p1 <- apply(geno[, 25:49], 1, function(x) {sum(as.numeric(as.character(x)))})
geno$p1 <- geno$p1/25
geno$p2 <- apply(geno[, 50:64], 1, function(x) {sum(as.numeric(as.character(x)))})
geno$p2 <- geno$p2/15
#calculating fst values
geno$fst <- with(geno, ((p1-p)^2 + (p2-p)^2)/(2*p*(1-p)) )
#to output fst values
write.table(geno, "fst.csv", sep=",", row.names = FALSE, quote=FALSE)
```

```{r}
#to plot the fst values
fst <- read.csv("fst.csv")
plot(fst$pos, fst$fst, xlab="Physical position", ylab="Fst value", main="")
```
